
import localFont from "next/font/local";
import "../globals.css";
import { getServerSession } from "next-auth";
import { authOptions } from "../api/auth/[...nextauth]/route";
import { redirect } from "next/navigation";
import Image from "next/image";

const geistSans = localFont({
  src: "../fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "../fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Linktree clone ",
  description: "Generated by le sang ",
};

export default async function AppLayout({ children }) {
    const session = await getServerSession(authOptions)
    if(!session){
        return redirect('/');
    }
    console.log(session);
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <main className="flex min-h-screen ">
         <aside className="bg-blue-100 w-48 p-4">
            aside stuff
            <div>
                <Image src={session.user.image} alt={'avatar'} width={60} height={60} />
            </div>
         </aside>
          <div className=" max-w-4xl mx-auto p-6 ">{children}</div>
        </main>
      </body>
    </html>
  );
}
