import { getServerSession } from "next-auth";
import localFont from "next/font/local";
import Image from "next/image";
import { redirect } from "next/navigation";
//import { headers } from "next/headers";
import { authOptions } from "../api/auth/[...nextauth]/route";
import "../globals.css";
import AppSidebar from "@/components/layout/AppSidebar";

const geistSans = localFont({
  src: "../fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "../fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Linktree clone ",
  description: "Generated by le sang ",
};

export default async function AppTemplate({ children, ...rest }) {
  //const headersList = headers();
  //console.log([...headersList]);
  //const url = headersList.get('next-url');
  //console.log(url)
  const session = await getServerSession(authOptions);
  if (!session) {
    return redirect("/");
  }
 // console.log(session);
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <main className="flex min-h-screen ">
          <aside className="bg-white w-48 p-4 shadow">
            <div className="rounded-full overflow-hidden w-24 mx-auto">
              <Image
                src={session.user.image}
                alt={"avatar"}
                width={256}
                height={256}
              />
            </div>
            <div className="text-center">
             <AppSidebar />
            </div>
          </aside>
          <div className="grow">
            <div className="bg-white m-8 p-4 shadow">{children}</div>
          </div>
        </main>
      </body>
    </html>
  );
}
